// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'loader-3d-move': string;
  'loader-bottom-outer-move': string;
  'loader-top-outer-move': string;
  'loader3dBottom': string;
  'loader3dBottomOuter': string;
  'loader3dContainer': string;
  'loader3dFace': string;
  'loader3dFaceBack': string;
  'loader3dFaceFront': string;
  'loader3dFaceRight': string;
  'loader3dMiddle': string;
  'loader3dTop': string;
  'loader3dTopOuter': string;
}
export const cssExports: CssExports;
export default cssExports;
