// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'heavy': string;
  'heavySmall': string;
  'heavyTiny': string;
  'hidden': string;
  'intro': string;
  'regular': string;
  'regularSmall': string;
  'regularTiny': string;
  'text': string;
}
export const cssExports: CssExports;
export default cssExports;
