// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'spinner-3d-move': string;
  'spinner-bottom-outer-move': string;
  'spinner-top-outer-move': string;
  'spinner3dBottomOuter': string;
  'spinner3dContainer': string;
  'spinner3dFace': string;
  'spinner3dFaceBack': string;
  'spinner3dFaceFront': string;
  'spinner3dFaceGroup': string;
  'spinner3dFaceRight': string;
  'spinner3dTopOuter': string;
}
export const cssExports: CssExports;
export default cssExports;
