// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'button': string;
  'buttonGroup': string;
  'buttonGroup--large': string;
  'buttonGroup--medium': string;
  'buttonGroup--small': string;
  'disabled': string;
  'fullWidth': string;
  'grey': string;
  'large': string;
  'medium': string;
  'primary': string;
  'red': string;
  'redOutline': string;
  'secondary': string;
  'small': string;
  'transparent': string;
}
export const cssExports: CssExports;
export default cssExports;
