// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'heading': string;
  'heading1': string;
  'heading2': string;
  'heading3': string;
}
export const cssExports: CssExports;
export default cssExports;
